<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Docker.DotNet" Version="3.125.15" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
      <PackageReference Include="MudBlazor" Version="9.8.0" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Zick.GameScheduler.Backend.Data\Zick.GameScheduler.Backend.Data.csproj" />
      <ProjectReference Include="..\Zick.GameScheduler.Backend.EntryListGenerator\Zick.GameScheduler.Backend.EntryListGenerator.csproj" />
      <ProjectReference Include="..\Zick.GameScheduler.Backend.ResultConsumer\Zick.GameScheduler.Backend.ResultConsumer.csproj" />
      <ProjectReference Include="..\Zick.GameScheduler.Backend.Scheduler\Zick.GameScheduler.Backend.Scheduler.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="resultExample.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
