// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zick.GameScheduler.Backend.Data;
using Zick.GameScheduler.Backend.Data.Models;

#nullable disable

namespace Zick.GameScheduler.Backend.Data.Migrations
{
    [DbContext(typeof(ApplicationContext<RacingUserIdentity>))]
    [Migration("20260820125756_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Car<RacingUserIdentity>RacingClass<RacingUserIdentity>", b =>
                {
                    b.Property<Guid>("CarsId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassesAbbreviation")
                        .HasColumnType("text");

                    b.HasKey("CarsId", "ClassesAbbreviation");

                    b.HasIndex("ClassesAbbreviation");

                    b.ToTable("Car<RacingUserIdentity>RacingClass<RacingUserIdentity>");
                });

            modelBuilder.Entity("League<RacingUserIdentity>RacingClass<RacingUserIdentity>", b =>
                {
                    b.Property<string>("ClassesAbbreviation")
                        .HasColumnType("text");

                    b.Property<Guid>("LeaguesId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassesAbbreviation", "LeaguesId");

                    b.HasIndex("LeaguesId");

                    b.ToTable("League<RacingUserIdentity>RacingClass<RacingUserIdentity>");
                });

            modelBuilder.Entity("LeagueSession<RacingUserIdentity>RacingUserIdentity", b =>
                {
                    b.Property<string>("RegistrationsId")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionsId")
                        .HasColumnType("uuid");

                    b.HasKey("RegistrationsId", "SessionsId");

                    b.HasIndex("SessionsId");

                    b.ToTable("LeagueSession<RacingUserIdentity>RacingUserIdentity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.Car<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrentTrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Practice", "Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>.Practice#SessionData", b1 =>
                        {
                            b1.Property<int?>("DurationInMinutes")
                                .HasColumnType("integer");

                            b1.Property<int?>("Laps")
                                .HasColumnType("integer");

                            b1.Property<string>("SessionName")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Qualify", "Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>.Qualify#SessionData", b1 =>
                        {
                            b1.Property<int?>("DurationInMinutes")
                                .HasColumnType("integer");

                            b1.Property<int?>("Laps")
                                .HasColumnType("integer");

                            b1.Property<string>("SessionName")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Race", "Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>.Race#SessionData", b1 =>
                        {
                            b1.Property<int?>("DurationInMinutes")
                                .HasColumnType("integer");

                            b1.Property<int?>("Laps")
                                .HasColumnType("integer");

                            b1.Property<string>("SessionName")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CurrentTrackId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.LeagueSession<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TrackId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.RacingClass<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Abbreviation");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SteamId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.Track<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Car<RacingUserIdentity>RacingClass<RacingUserIdentity>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.Car<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingClass<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", null)
                        .WithMany()
                        .HasForeignKey("ClassesAbbreviation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("League<RacingUserIdentity>RacingClass<RacingUserIdentity>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingClass<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", null)
                        .WithMany()
                        .HasForeignKey("ClassesAbbreviation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", null)
                        .WithMany()
                        .HasForeignKey("LeaguesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueSession<RacingUserIdentity>RacingUserIdentity", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("RegistrationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.LeagueSession<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", null)
                        .WithMany()
                        .HasForeignKey("SessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.Track<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", "CurrentTrack")
                        .WithMany("CurrentEvents")
                        .HasForeignKey("CurrentTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentTrack");
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.LeagueSession<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.League<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zick.GameScheduler.Backend.Data.Models.Track<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", "Track")
                        .WithMany("Sessions")
                        .HasForeignKey("TrackId");

                    b.Navigation("League");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Zick.GameScheduler.Backend.Data.Models.Track<Zick.GameScheduler.Backend.Data.Models.RacingUserIdentity>", b =>
                {
                    b.Navigation("CurrentEvents");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
